language: go
go:
  - 1.6
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
before_script:
  - go get -d ./...
script:
  - golint ./...
  - go vet ./...
  - go test -v ./...
  - if ! $HOME/gopath/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN; then echo "Coveralls not available."; fi
  - go build ./...
